# .github/workflows/check.yml

name: Check project

on:
  - push
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Ruff
        run: poetry run ruff check

      - name: Mypy
        run: poetry run mypy --install-types --check-untyped-defs --non-interactive .

      - name: Pytest
        run: poetry run pytest --showlocals --tb=auto -ra --cov-branch --cov-report=term-missing
