name: Linters and Tests

on: [push, pull_request]
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install
          mkdir .mypy_cache

      - name: Ruff
        run: poetry run ruff check

      - name: Pylint
        run: poetry run pylint djpoe/djpoe tests

      - name: Mypy
        run: poetry run mypy --install-types --check-untyped-defs --non-interactive .

  pytest:
    needs:
      - run-linters

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Pytest
        run: poetry run pytest --showlocals --tb=auto -ra --cov-branch --cov-report=term-missing
