name: Linters

on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry and dependeencies
        run: |
          pip install poetry
          poetry install

      - name: Run Ruff
        run: poetry run ruff check
